quantity = int(input("จำนวนปืนที่รับมาขาย :"))
cost_price = int(input("ต้นทุนของปืนที่รับมา :"))
sell_price = int(input("ราคาที่จะนำไปขายต่อ :"))
team_member = int(input("จำนวนลูกน้องในทีมที่ไปทำงาน :"))
print(cost_price)
print(sell_price)
print(cost_price - sell_price)
print()